defmodule NexusUiWeb.TransformationLive do
  @moduledoc """
  Displays the compiled transformation Python code for a pipeline.
  Users can view forward/reverse transforms, edit them, run test records through them,
  and trigger the agent to regenerate.
  """
  use NexusUiWeb, :live_view

  alias NexusUi.ApiClient

  @impl true
  def mount(%{"id" => pipeline_id}, _session, socket) do
    pipeline = load_pipeline(pipeline_id)
    transformation = load_transformation(pipeline_id)

    {:ok,
     socket
     |> assign(:page_title, "Transformation — #{pipeline["name"]}")
     |> assign(:pipeline, pipeline)
     |> assign(:pipeline_id, pipeline_id)
     |> assign(:transformation, transformation)
     |> assign(:active_tab, "forward")
     |> assign(:test_input, "{}")
     |> assign(:test_output, nil)
     |> assign(:test_error, nil)
     |> assign(:regenerating, false)}
  end

  @impl true
  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, :active_tab, tab)}
  end

  def handle_event("update_test_input", %{"value" => val}, socket) do
    {:noreply, assign(socket, :test_input, val)}
  end

  def handle_event("run_test", _, socket) do
    input =
      case Jason.decode(socket.assigns.test_input) do
        {:ok, parsed} -> parsed
        {:error, _} -> nil
      end

    if is_nil(input) do
      {:noreply, assign(socket, :test_error, "Invalid JSON input")}
    else
      case ApiClient.test_transformation(socket.assigns.pipeline_id, input) do
        {:ok, result} ->
          {:noreply,
           socket
           |> assign(:test_output, Jason.encode!(result["output"], pretty: true))
           |> assign(:test_error, result["error"])}

        {:error, err} ->
          {:noreply, assign(socket, :test_error, inspect(err.body))}
      end
    end
  end

  def handle_event("regenerate", _, socket) do
    case ApiClient.regenerate_transformation(socket.assigns.pipeline_id) do
      {:ok, _} ->
        {:noreply,
         socket
         |> assign(:regenerating, true)
         |> put_flash(:info, "Regeneration requested. Agent is working...")}

      {:error, err} ->
        {:noreply, put_flash(socket, :error, inspect(err.body))}
    end
  end

  def handle_event("save_code", %{"code" => code}, socket) do
    tab = socket.assigns.active_tab

    params =
      case tab do
        "forward" -> %{forward_code: code}
        "reverse" -> %{reverse_code: code}
        _ -> %{}
      end

    case ApiClient.update_transformation(socket.assigns.pipeline_id, params) do
      {:ok, t} ->
        {:noreply,
         socket
         |> assign(:transformation, t)
         |> put_flash(:info, "Saved")}

      {:error, err} ->
        {:noreply, put_flash(socket, :error, inspect(err.body))}
    end
  end

  defp load_pipeline(id) do
    case ApiClient.get_pipeline(id) do
      {:ok, p} -> p
      _ -> %{}
    end
  end

  defp load_transformation(pipeline_id) do
    case ApiClient.get_transformation(pipeline_id) do
      {:ok, t} -> t
      _ -> %{"forward_code" => "# No transformation generated yet", "reverse_code" => "# No transformation generated yet"}
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="p-6 space-y-6">
      <div class="flex justify-between items-center">
        <div>
          <h1 class="text-2xl font-bold text-gray-900">Transformation Code</h1>
          <p class="text-gray-500 text-sm mt-1"><%= @pipeline["name"] %></p>
        </div>
        <div class="flex gap-2">
          <.link navigate={"/pipelines/#{@pipeline_id}/mappings"} class="btn-secondary">
            ← Edit Mappings
          </.link>
          <button phx-click="regenerate" disabled={@regenerating} class="btn-secondary">
            <%= if @regenerating, do: "Regenerating...", else: "✦ Regenerate via Agent" %>
          </button>
        </div>
      </div>

      <%!-- Validation badge --%>
      <%= if @transformation["validation_passed"] do %>
        <div class="flex items-center gap-2 text-green-700 bg-green-50 border border-green-200 rounded px-4 py-2 text-sm">
          ✓ Transformation validated — generated by <%= @transformation["generated_by"] %>
        </div>
      <% else %>
        <div class="flex items-center gap-2 text-yellow-700 bg-yellow-50 border border-yellow-200 rounded px-4 py-2 text-sm">
          ⚠ Not yet validated
        </div>
      <% end %>

      <%!-- Tab switcher --%>
      <div class="border-b flex gap-0">
        <button phx-click="switch_tab" phx-value-tab="forward"
                class={"px-4 py-2 text-sm font-medium border-b-2 " <>
                       if @active_tab == "forward", do: "border-blue-500 text-blue-600", else: "border-transparent text-gray-500"}>
          Forward (source → target)
        </button>
        <button phx-click="switch_tab" phx-value-tab="reverse"
                class={"px-4 py-2 text-sm font-medium border-b-2 " <>
                       if @active_tab == "reverse", do: "border-blue-500 text-blue-600", else: "border-transparent text-gray-500"}>
          Reverse (target → source)
        </button>
      </div>

      <%!-- Code display --%>
      <div class="bg-gray-900 rounded-lg overflow-hidden">
        <div class="flex justify-between items-center px-4 py-2 bg-gray-800">
          <span class="text-gray-400 text-xs font-mono">
            transform_<%= @active_tab %>(record: dict, context: dict) -> dict
          </span>
          <button phx-click="save_code"
                  phx-value-code={if @active_tab == "forward", do: @transformation["forward_code"], else: @transformation["reverse_code"]}
                  class="text-xs text-gray-400 hover:text-white">
            Save
          </button>
        </div>
        <pre class="p-4 text-green-300 text-sm overflow-x-auto font-mono whitespace-pre"><%= if @active_tab == "forward", do: @transformation["forward_code"], else: @transformation["reverse_code"] %></pre>
      </div>

      <%!-- Test runner --%>
      <div class="bg-white rounded-lg shadow">
        <div class="px-4 py-3 border-b">
          <h2 class="font-semibold text-gray-700">Test Runner</h2>
          <p class="text-xs text-gray-500 mt-0.5">
            Paste a sample record and run it through the transformation
          </p>
        </div>
        <div class="grid grid-cols-2 gap-4 p-4">
          <div>
            <label class="text-xs text-gray-500 font-medium">Input Record (JSON)</label>
            <textarea
              phx-blur="update_test_input"
              phx-value-value={@test_input}
              rows="10"
              class="w-full mt-1 rounded border border-gray-300 px-3 py-2 text-sm font-mono"
              placeholder='{"RECORDNO": "1234", "VENDORNAME": "Acme Corp"}'
            ><%= @test_input %></textarea>
            <button phx-click="run_test" class="btn-primary mt-2 text-sm">
              ▶ Run Test
            </button>
          </div>
          <div>
            <label class="text-xs text-gray-500 font-medium">Output</label>
            <%= if @test_error do %>
              <div class="mt-1 bg-red-50 border border-red-200 rounded p-3 text-red-700 text-sm font-mono">
                <%= @test_error %>
              </div>
            <% end %>
            <%= if @test_output do %>
              <pre class="mt-1 bg-gray-50 border border-gray-200 rounded p-3 text-sm font-mono overflow-auto h-48"><%= @test_output %></pre>
            <% end %>
            <%= if is_nil(@test_output) and is_nil(@test_error) do %>
              <div class="mt-1 bg-gray-50 border border-dashed border-gray-300 rounded p-3 text-gray-400 text-sm">
                Output will appear here after running the test.
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    """
  end
end
